---
- name: download maven artifact from nexus
  maven_artifact:
    version: "{{ version }}"
    group_id: com.fujitsu.fs.demo
    artifact_id: DEMO_File_EAR
    extension: war
    repository_url: 'http://62.60.42.82:8081/repository/maven-releases/'
    username: 
    password: 
    dest: ./

- name: copy war
  copy:
    src: "DEMO_File_WAR-{{ version }}.war"
    remote_src: yes
    dest: "/opt/apache-tomcat-8.5.16/webapps/DEMO_File_WAR-{{ version }}.war"
    mode: 0744
