---
# tasks file for loadJsonVars
- set_fact:
    artifact_name: poa-bal-json
    artifact_ext: json

- name: download release json artifact from nexus
  maven_artifact:
    version: "{{ version }}"
    group_id: com.fujitsu.fs.poa.release
    artifact_id: "{{artifact_name}}"
    extension: "{{artifact_ext}}"
    repository_url: 'http://62.60.42.82:8081/repository/maven-releases/'
    username: 
    password: 
    dest: ./
    
#- name: Import variables from json file


- shell: pwd

#- shell: ls /var/lib/jenkins/workspace/martin_in_test_pipeline/

- name: JSON file
  debug:
    msg: "{{artifact_name}}-{{version}}.{{artifact_ext}}"

- name: Set jsonfile name separately as it cannot be defined and used in the same set_fact as the lookup
  set_fact:
    jsonfile: "/var/lib/jenkins/workspace/martin_in_test_pipeline/{{artifact_name}}-{{version}}.{{artifact_ext}}"

- name: test
  shell: "{{ item }}"
  with_items:
    - ls -ltr ./
    - ls -ltr ../
    - pwd
    - sudo ls -ltr /var
    - sudo ls -ltr /var/lib/
    - sudo ls -ltr /var/lib/jenkins/
    - sudo ls -ltr /var/lib/jenkins/workspace/
    - sudo ls -ltr /var/lib/jenkins/workspace/martin_in_test_pipeline/
    - "cat {{ jsonfile }}" 

- name: Read release file
  set_fact:
    jsonVar: "{{ lookup('file', jsonfile) | regex_replace('\\[') | regex_replace('\\]') | from_json}}"


- debug:
    msg: "{{env}}"