---
# tasks file for loadJsonVars
- set_fact:
    artifact_name: poa-bal-json
    artifact_ext: json

- name: download release json artifact from nexus
  maven_artifact:
    version: "{{ version }}"
    group_id: com.fujitsu.fs.poa.release
    artifact_id: "{{artifact_name}}"
    extension: "{{artifact_ext}}"
    repository_url: 'http://62.60.42.82:8081/repository/maven-releases/'
    username: 
    password: 
    dest: ./
    mode: 0644
    
#- name: Import variables from json file


- shell: pwd

#- shell: ls /var/lib/jenkins/workspace/martin_in_test_pipeline/

- name: JSON file
  debug:
    msg: "{{artifact_name}}-{{version}}.{{artifact_ext}}"

- name: Set jsonfile name separately as it cannot be defined and used in the same set_fact as the lookup
  set_fact:
    jsonfile: "/home/k5user/{{artifact_name}}-{{version}}.{{artifact_ext}}"

- name: test
  shell: "{{ item }}"
  with_items:
    - ls -ltr ./
    - ls -ltr ../
    - pwd
    - ls -ltr /home/k5user
    - "cat {{ jsonfile }}" 
    - "cp {{ jsonfile }} /home/k5user/release.json" 
#    - "chmod 777 {{ jsonfile }}"
  become_user: k5user
  become: true

- name: display multiple file contents
  debug: var=item
  with_file:
    - '/home/k5user/release.json'
    - "{{ jsonfile }}"
  become_user: k5user
  become: true

- name: Read release file
  set_fact:
#    jsonVar: "{{ lookup('file', jsonfile) | regex_replace('\\[') | regex_replace('\\]') | from_json}}"
    jsonVar: "{{ lookup('file', '/home/k5user/release.json') | regex_replace('\\[') | regex_replace('\\]') | from_json}}"
  become_user: k5user
  become: true

- debug:
    msg: "{{env}}"