---
# tasks file for loadJsonVars
- set_fact:
    artifact_name: poa-bal-json
    artifact_ext: json

- name: download release json artifact from nexus
  maven_artifact:
    version: "{{ version }}"
    group_id: com.fujitsu.fs.poa.release
    artifact_id: "{{artifact_name}}"
    extension: "{{artifact_ext}}"
    repository_url: 'http://62.60.42.82:8081/repository/maven-releases/'
    username: 
    password: 
    dest: ./
    
- name: Import variables from json file
  shell: ls ./

- shell: pwd


- name: JSON file
  debug:
    msg: "{{artifact_name}}-{{version}}.{{artifact_ext}}"
    
- name: Set jsonfile name separately as it cannot be defined and used in the same set_fact as the lookup
  set_fact:
    jsonfile: "./{{artifact_name}}-{{version}}.{{artifact_ext}}"

- shell: "{{cat jsonfile}}"" 

- name: Read release file
  set_fact:
    jsonVar: "{{ lookup('file', jsonfile) | regex_replace('\\[') | regex_replace('\\]') | from_json}}"


- debug:
    msg: "{{env}}"