---
# tasks file for fetchJsonVars
- set_fact:
    artifact_name: poa-bal-json
    artifact_ext: json

- name: download release json artifact from nexus to remote machine
  maven_artifact:
    version: "{{ version }}"
    group_id: com.fujitsu.fs.poa.release
    artifact_id: "{{artifact_name}}"
    extension: "{{artifact_ext}}"
    repository_url: 'http://62.60.42.82:8081/repository/maven-releases/'
    username: 
    password: 
    dest: ./
    mode: 0644
    
- name: Set jsonfile name separately as it cannot be defined and used in the same set_fact as the lookup
  set_fact:
    jsonfile: "{{artifact_name}}-{{version}}.{{artifact_ext}}"

- name: get json file contents from remote machine
  command: "cat {{ jsonfile }}"
  register: jsonFileContents

- name: Read release file
  set_fact:
    jsonVar: "{{ jsonFileContents.stdout | regex_replace('\\[') | regex_replace('\\]') | from_json}}"

- name: Content of release file
  debug:
    msg: "{{ jsonVar }}"

- name: Replace version numbers in file
  local_action:
    module: replace
    path: 'group_vars/dev.yml'
    regexp: "{{ item }}_VERSION:.*"
    replace: "{{ item }}_VERSION: {{jsonVar.artifacts[item].artifact_version}}"
  with_items: "{{ jsonVar.artifacts }}"

- name: cat group_vars/dev.yml
  local_action:
    module: command cat group_vars/dev.yml
  register: aftercontent

- name: Content of release file
  debug:
    msg: "{{ aftercontent }}"

- name: git diff
  local_action:
    module: command git diff
