---
- hosts: all
  tasks:
 #   - name: Make sure that we can connect to the machine
 #     ping:
    - name: download release json artifact from nexus
      maven_artifact:
        version: 10.22
        group_id: com.fujitsu.fs.poa.release
        artifact_id: poa-bal-json
        extension: json
        repository_url: 'http://62.60.42.82:8081/repository/maven-releases/'
        username: 
        password: 
        dest: ./

    - name: download maven aritfact from nexu
      maven_artifact:
        version: 10.9
        group_id: com.fujitsu.fs.demo
        artifact_id: DEMO_File_WAR
        extension: war
        repository_url: 'http://62.60.42.82:8081/repository/maven-releases/'
        username: 
        password: 
        dest: ./
    
    - name: copy war
      copy:
        src: DEMO_File_WAR-10.9.war
        remote_src: yes
        dest: /opt/apache-tomcat-8.5.16/webapps/DEMO_File_WAR-10.9.war
        mode: 0744

    # - name: copy war
    #   copy: src=./RESTfulExample.war dest=/opt/apache-tomcat-8.5.16/webapps/RESTfulExample.war  mode=0744
