---
- hosts: all
  tasks:
 #   - name: Make sure that we can connect to the machine
 #     ping:

    - name: copy war
      copy: src=./RESTfulExample.war dest=/opt/apache-tomcat-8.5.16/webapps/RESTfulExample.war  mode=0744